collections:
  rules:
    output: true

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "autolink", "strikethrough", "with_toc_data"]

markdown: kramdown

highlighter: rouge